/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lJzfYmbcdtA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { AvatarImage, Avatar } from "@/components/ui/avatar";
import { Button } from "./ui/button";

export function BlogPosts() {
  return (
    <div className="flex flex-col min-h-[100dvh] mx-10">
      <div className="flex-1 bg-gray-100/90 dark:bg-gray-800/90 rounded-md ">
        <div className="flex items-center mt-10  justify-around">
          <h1 className="text-xl font-bold uppercase ">Threads</h1>
          <Button className="" color="primary">
            Create Thread
          </Button>
        </div>
        <div className="container grid items-start gap-6 px-4 py-6 md:py-12 lg:px-6 lg:gap-10 xl:grid-cols-4 xl:gap-16">
          <BlogPost />
        </div>
      </div>
    </div>
  );
}

function BlogPost({ userName }: any) {
  return (
    <div className="space-y-4 xl:col-start-2 xl:col-span-2 xl:order-last">
      <div className="flex items-center space-x-4">
        <div className="flex items-center space-x-2">
          <Avatar className="w-12 h-12">
            <AvatarImage alt="Avatar" src="/avatar.jpg" />
          </Avatar>
          <div className="flex flex-col">
            <Link
              className="font-semibold hover:underline underline-offset-4"
              href="#"
            >
              miked
            </Link>
            <time className="text-xs text-gray-500 dark:text-gray-400">
              2 minutes ago
            </time>
          </div>
        </div>
        <div className="relative">
          <div className="rounded-md p-2 hover:bg-gray-100/40 focus-visible:outline-none dark:hover:bg-gray-800/40">
            <CircleEllipsisIcon className="w-4 h-4" />
            <span className="sr-only">Menu</span>
          </div>
        </div>
      </div>
      <div className="space-y-2 text-base leading-8">
        <p>Just finished a 5k run. I'm exhausted but feeling great!</p>
        <img
          alt="Image"
          className="aspect-video overflow-hidden rounded-xl object-cover object-center"
          height="250"
          src="/placeholder.svg"
          width="500"
        />
      </div>
    </div>
  );
}

function CircleEllipsisIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M17 12h.01" />
      <path d="M12 12h.01" />
      <path d="M7 12h.01" />
    </svg>
  );
}
